{
  "name": "cyclesyncing",
  "compatibility_date": "2025-08-12",
  "builds": [
    {
      "src": "package.json",
      "use": "@cloudflare/next-on-pages"
    }
  ],
  "routes": [
    {
      "pattern": "/*",
      "dest": "/"
    }
  ],
  "env": {
    "NEXT_PUBLIC_SUPABASE_URL": "https://gpumqfjnwwhyksogefsk.supabase.co",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwdW1xZmpud3doeWtzb2dlZnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTM5NDMwMjYsImV4cCI6MjAwOTUxOTAyNn0.bOSWJajwPzDcZZPQYk0eAF9FkOrJ5_JKB5ym-QSOYx4",
    "MISTRAL_API_KEY": "hKCnOoLbEXL18JLuj5N2wzTlwXKMmVFr",
    "NEXT_PUBLIC_APP_NAME": "CycleSync",
    "NEXT_PUBLIC_APP_URL": "https://cyclesyncing.pages.dev"
  }
}